# site settings
title: Spencer Bartlett
subtitle:
email: spencerbartlett@vt.edu
description: I'm a Computer Science student at Virginia Tech interested in backend dev, robotics and artificial intelligence. Also a gamer, climber, and runner.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://spencerbartlett.com # the base hostname & protocol for your site
author: Spencer
street_address:
city: Blacksburg
state: VA
zip_code: 24061
country: United States of America
phone: (571) 379-3276

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sbmercury
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
